### ISSUE TITLE
2차 스터디 종료 (22.12.17 17:00 ~ 19:30)

### ISSUE THREAD

**Issue by rasz60** [rasz60/idme#2]
#### 1) 완료 사항
  - 김가율 : ORACLE 설치, Eclipse 설치
  - 김진웅 : ORACLE 설치
  - 진우람 : ORACLE 설치, STS 설치

#### 2) 필요 사항
  - 김가율 : ORACLE 초기설정, 이클립스(STS, GIT) 환경 설정
  - 김진웅 : ORACLE 초기설정, 테스트 데이터 수집/공유
  - 진우람 : ORACLE 초기설정

## 2. 스터디 내용
 - 이전 작업한 상품 리스트 기준으로 테스트 데이터 생성 (리스트 전달 : 김가율 -> 김진웅)
 - Debug  : war-maven plugin 추가 (pom.xml)
 - 차후 프로젝트 아이디어 공유
  (1) 시각장애인 버스 알림 어플리케이션
      : 버스 도착 정보 전광판을 인지하기 어려운 시각 장애인에게 버스 도착정보 알림
      : 버스 기사님에게도 도착할 버스 정류장에 시각 장애인이 탑승 대기 중임을 알림
  (2) 운동 기록 용 어플리케이션
      : GPS 기능 활용 이동 거리량, 운동 종류에 따른 세트 수, 타이머 기능 활용 소요 시간 등을 수집하여 소비된 칼로리 출력
      : 특정 일에 총 운동 시간, 칼로리 소비량 등을 기록
  (3) 스터디 플래너 어플리케이션
      : 캘린더, 지도 등 API 이용하여 스터디 일정, 진행 상황, 모임 장소 등 스터디에 필요한 기능 구현
      : 현재 공부 혹은 프로젝트 작업 중인 경우 로그인하여 작업 시간 기록과 다른 유저에게 현재 공부 중 임을 알릴 수 있는 기능

## 3. 이 후 공지
  - 환경 설정 : 설치 및 초기 설정 후 테스트 데이터 Insert, 프로젝트 구동까지 확인 (22.12.20 (화) 까지)
  - 설정 완료된 Main branch 프로젝트를 각자의 branch 생성하여 내려받은 후 작업 시작

**Comment by Billy-Jin** [comment]
기본 설정 완료 후 서버 실행 확인, 상품리스트 추가 및 사진 추가

**Comment by rasz60** [comment]
환경설정 22.12.31(토) 까지로 연장
